import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { CreatorTake } from '../services/creator';

type Props = { enabled: boolean; takes: CreatorTake[]; onToggle: () => void; onSelectTake: (take: CreatorTake) => void; onGenerateAll: () => void; busy: boolean };

export function CreatorMode({ enabled, takes, onToggle, onSelectTake, onGenerateAll, busy }: Props) {
  return <View style={styles.container}>
    <View style={styles.header}><View><Text style={styles.label}>CREATOR MODE</Text><Text style={styles.title}>Build a narration take by take.</Text></View><Pressable accessibilityRole="switch" accessibilityState={{ checked: enabled }} onPress={onToggle} style={[styles.toggle, enabled && styles.toggleActive]}><View style={[styles.knob, enabled && styles.knobActive]} /></Pressable></View>
    {enabled && <>
      <Text style={styles.help}>Long scripts are split into manageable takes so you can rehearse and regenerate individual sections.</Text>
      <View style={styles.takeList}>{takes.map((take) => <Pressable key={take.id} accessibilityRole="button" accessibilityState={{ selected: take.status === 'current' }} onPress={() => onSelectTake(take)} style={[styles.take, take.status === 'current' && styles.takeCurrent]}><View style={styles.takeNumber}><Text style={styles.takeNumberText}>{take.index + 1}</Text></View><View style={styles.takeInfo}><Text style={styles.takeText} numberOfLines={3}>{take.text}</Text><Text style={styles.takeMeta}>{take.status === 'done' ? 'Generated' : take.status === 'current' ? 'Current take' : 'Ready'}</Text></View></Pressable>)}</View>
      <Pressable accessibilityRole="button" accessibilityState={{ disabled: busy }} disabled={busy || takes.length === 0} onPress={onGenerateAll} style={styles.generateAll}><Text style={styles.generateAllText}>{busy ? 'Generating takes…' : 'Generate All Takes'}</Text></Pressable>
    </>}
  </View>;
}

const styles = StyleSheet.create({ container: { backgroundColor: '#13161D', borderColor: '#252A35', borderRadius: 18, borderWidth: 1, marginBottom: 24, padding: 16 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, label: { color: '#858D9D', fontFamily: 'Vazirmatn_700Bold', fontSize: 10, letterSpacing: 1.4 }, title: { color: '#F4F6FA', fontFamily: 'Vazirmatn_500Medium', fontSize: 14, marginTop: 5 }, toggle: { backgroundColor: '#252A35', borderRadius: 14, height: 28, justifyContent: 'center', paddingHorizontal: 3, width: 50 }, toggleActive: { backgroundColor: '#A9B3FF' }, knob: { backgroundColor: '#858D9D', borderRadius: 11, height: 22, width: 22 }, knobActive: { alignSelf: 'flex-end', backgroundColor: '#0B0D12' }, help: { color: '#727B8C', fontFamily: 'Vazirmatn_400Regular', fontSize: 11, lineHeight: 18, marginTop: 10 }, takeList: { marginTop: 12 }, take: { alignItems: 'center', borderColor: '#252A35', borderRadius: 13, borderWidth: 1, flexDirection: 'row', marginTop: 7, padding: 10 }, takeCurrent: { borderColor: '#59638C' }, takeNumber: { alignItems: 'center', backgroundColor: '#202532', borderRadius: 10, height: 32, justifyContent: 'center', width: 32 }, takeNumberText: { color: '#A9B3FF', fontFamily: 'Vazirmatn_700Bold', fontSize: 11 }, takeInfo: { flex: 1, marginLeft: 10 }, takeText: { color: '#DCE0E8', fontFamily: 'Vazirmatn_400Regular', fontSize: 12, lineHeight: 18 }, takeMeta: { color: '#626978', fontFamily: 'Vazirmatn_400Regular', fontSize: 9, marginTop: 3 }, generateAll: { alignItems: 'center', borderColor: '#59638C', borderRadius: 12, borderWidth: 1, marginTop: 10, paddingVertical: 10 }, generateAllText: { color: '#A9B3FF', fontFamily: 'Vazirmatn_700Bold', fontSize: 11 } });
