import { Pressable, StyleSheet, Text, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { Copy } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { Trash2 } from 'lucide-react-native';
import type { SpeechHistoryItem } from '../services/history';
import { FavoriteButton } from './FavoriteButton';

type Props = { items: SpeechHistoryItem[]; favoriteIds?: string[]; onToggleFavorite?: (id: string) => void; onSelect: (item: SpeechHistoryItem) => void; onDelete: (id: string) => void; onClear: () => void };

export function HistoryPanel({ items, favoriteIds = [], onToggleFavorite, onSelect, onDelete, onClear }: Props) {
  const [filter, setFilter] = useState<'recent' | 'favorites'>('recent');
  const copyText = async (text: string) => { await Clipboard.setStringAsync(text); };
  const visibleItems = useMemo(() => filter === 'favorites' ? items.filter((item) => favoriteIds.includes(item.id)) : items, [filter, favoriteIds, items]);
  if (!items.length) return <View style={styles.empty}><Text style={styles.emptyTitle}>Nothing here yet.</Text><Text style={styles.emptyText}>Generated speech will appear here automatically.</Text></View>;
  return <View style={styles.container}><View style={styles.header}><Text style={styles.title}>Speech history</Text><Pressable onPress={onClear}><Text style={styles.clear}>Clear</Text></Pressable></View><View style={styles.filters}><Pressable accessibilityRole="button" accessibilityState={{ selected: filter === 'recent' }} onPress={() => setFilter('recent')} style={[styles.filter, filter === 'recent' && styles.filterActive]}><Text style={[styles.filterText, filter === 'recent' && styles.filterTextActive]}>Recent</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{ selected: filter === 'favorites' }} onPress={() => setFilter('favorites')} style={[styles.filter, filter === 'favorites' && styles.filterActive]}><Text style={[styles.filterText, filter === 'favorites' && styles.filterTextActive]}>★ Favorites</Text></Pressable></View>
    {visibleItems.map((item) => <View key={item.id} style={styles.row}><Pressable accessibilityRole="button" onPress={() => onSelect(item)} style={styles.item}><Text numberOfLines={2} style={styles.text}>{item.text}</Text><Text style={styles.meta}>{item.voiceName} · {new Date(item.createdAt).toLocaleDateString()}</Text></Pressable><FavoriteButton active={favoriteIds.includes(item.id)} label="speech" onPress={() => onToggleFavorite?.(item.id)} /><Pressable accessibilityRole="button" accessibilityLabel="Copy history text" hitSlop={10} onPress={() => void copyText(item.text)} style={styles.copyButton}><Copy size={17} color="#727B8C" strokeWidth={1.8} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Delete history item" hitSlop={10} onPress={() => onDelete(item.id)} style={styles.deleteButton}><Trash2 size={18} color="#727B8C" strokeWidth={1.8} /></Pressable></View>)}
  </View>;
}

const styles = StyleSheet.create({ container: { marginBottom: 24 }, filters: { flexDirection: 'row', gap: 8, marginBottom: 10 }, filter: { borderColor: '#252A35', borderRadius: 10, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 7 }, filterActive: { backgroundColor: '#A9B3FF', borderColor: '#A9B3FF' }, filterText: { color: '#858D9D', fontFamily: 'Vazirmatn_500Medium', fontSize: 11 }, filterTextActive: { color: '#0B0D12' }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, title: { color: '#F4F6FA', fontFamily: 'Vazirmatn_700Bold', fontSize: 15 }, clear: { color: '#A9B3FF', fontFamily: 'Vazirmatn_500Medium', fontSize: 12 }, row: { alignItems: 'center', backgroundColor: '#13161D', borderColor: '#252A35', borderRadius: 16, borderWidth: 1, flexDirection: 'row', marginBottom: 8, padding: 12 }, item: { flex: 1, paddingRight: 6 }, text: { color: '#DCE0E8', fontFamily: 'Vazirmatn_400Regular', fontSize: 13, lineHeight: 20 }, meta: { color: '#626978', fontFamily: 'Vazirmatn_400Regular', fontSize: 10, marginTop: 5 }, copyButton: { alignItems: 'center', justifyContent: 'center', minHeight: 40, minWidth: 40 }, deleteButton: { alignItems: 'center', justifyContent: 'center', minHeight: 40, minWidth: 40 }, empty: { backgroundColor: '#13161D', borderColor: '#252A35', borderRadius: 16, borderWidth: 1, marginBottom: 24, padding: 18 }, emptyTitle: { color: '#DCE0E8', fontFamily: 'Vazirmatn_500Medium', fontSize: 14 }, emptyText: { color: '#727B8C', fontFamily: 'Vazirmatn_400Regular', fontSize: 12, lineHeight: 19, marginTop: 5 } });
